### ISSUE TITLE
[DOCS] add GitBook integration configuration

### ISSUE THREAD

**Issue by basher83** [basher83/docs#11]
Need .gitbook.yaml 

example:

```
# GitBook ConfigurationAdd commentMore actions
root: ./docs/

# Structure
structure:
  readme: README.md
  summary: SUMMARY.md

# Git integration
git:
  branch: main

# Plugins
plugins:
  - search-plusAdd commentMore actions
  - sharing
  - fontsettings
  
# PDF optionsAdd commentMore actions
pdf:
  pageNumbers: true
  fontSize: 12
  fontFamily: "Arial"
  paperSize: a4
  margin:Add commentMore actions
    right: 62
    left: 62
    top: 56
    bottom: 56
  ```
